### PR TITLE
Django 3

### PR DESCRIPTION
**Pull request by Johnetordoff**

### CODE REVIEW

**Comment by Johnetordoff** [comment]
@chrisseto I took a stab at updating this to Django 3 for the upcoming OSF Django version bump, does this look good to you?

**Comment by chrisseto** [comment]
@Johnetordoff have you considered benchmarking include against Django's `prefetch_related`? My not so recent look suggests that the speed of the two are roughly comparable now!

Do you happen to know if there are any cases covered by include that aren't covered by `prefetch_related`? (There may have also been recently improvements here as well).

**Comment by Johnetordoff** [comment]
@chrisseto we considered it, but it seemed easier to just update the existing library then to change our queries. We are not wedded to either thing at this point, but I think `prefetch_related`'s roughly comparable in terms of performance, we'd just prefer to not make a big diff when upgrading to Django. But good input! Thanks!

**Comment by Johnetordoff** [comment]
@chrisseto We ultimately just switched to prefetch instead and it works great, so bye bye django-include.

**Pull request closed without merging**
